key_bindings:
  - { key: F11, action: ToggleFullscreen }

font:
  size: 6
  normal:
    # Anonymice
    # Fira Code
    # Blex Mono
    # Fura Code
    # Hack
    # Hasklug
    # Hurmit
    # Inconsolata
    # Jet Brains Mono
    # Sauce Code Pro
    # Literation Mono
    # family: Fira Code Nerd Font
    family: Jet Brains Mono Nerd Font

window:
  decorations: none

selection:
  save_to_clipboard: true

cursor:
  style: Underline

mouse:
  hide_when_typing: true

env:
  WINIT_HIDPI_FACTOR: '1'

schemes:
  dracula: &dracula
    # Colors (Dracula)
    # Default colors
    primary:
      background: '0x282a36'
      foreground: '0xf8f8f2'

      # Bright and dim foreground colors
      #
      # The dimmed foreground color is calculated automatically if it is not present.
      # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
      # is `false`, the normal foreground color will be used.
      #dim_foreground: '0x9a9a9a'
      #bright_foreground: '0xffffff'

    # Cursor colors
    #
    # Colors which should be used to draw the terminal cursor. If these are unset,
    # the cursor color will be the inverse of the cell color.
    cursor:
      text: '0x44475a'
      cursor: '0xf8f8f2'

    # Selection colors
    #
    # Colors which should be used to draw the selection area. If selection
    # background is unset, selection color will be the inverse of the cell colors.
    # If only text is unset the cell text color will remain the same.
    selection:
      text: '0xf8f8f2'
      background: '0x44475a'

    # Normal colors
    normal:
      black:   '0x000000'
      red:     '0xff5555'
      green:   '0x50fa7b'
      yellow:  '0xf1fa8c'
      blue:    '0xbd93f9'
      magenta: '0xff79c6'
      cyan:    '0x8be9fd'
      white:   '0xbfbfbf'

    # Bright colors
    bright:
      black:   '0x4d4d4d'
      red:     '0xff6e67'
      green:   '0x5af78e'
      yellow:  '0xf4f99d'
      blue:    '0xcaa9fa'
      magenta: '0xff92d0'
      cyan:    '0x9aedfe'
      white:   '0xe6e6e6'

    # Dim colors
    #
    # If the dim colors are not set, they will be calculated automatically based
    # on the `normal` colors.
    dim:
      black:   '0x14151b'
      red:     '0xff2222'
      green:   '0x1ef956'
      yellow:  '0xebf85b'
      blue:    '0x4d5b86'
      magenta: '0xff46b0'
      cyan:    '0x59dffc'
      white:   '0xe6e6d1'

    # Indexed Colors
    #
    # The indexed colors include all colors from 16 to 256.
    # When these are not set, they're filled with sensible defaults.
    #
    # Example:
    #   `- { index: 16, color: '0xff00ff' }`
    #
    indexed_colors: []

  # Tokyo Night theme, based on both:
  #   https://github.com/ghifarit53/tokyonight-vim
  #   https://github.com/enkia/tokyo-night-vscode-theme
  tokyo-night: &tokyo-night
    # Default colors
    primary:
      background: '0x1a1b26'
      foreground: '0xa9b1d6'

    # Normal colors
    normal:
      black:   '0x32344a'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan:    '0x449dab'
      white:   '0x787c99'

    # Bright colors
    bright:
      black:   '0x444b6a'
      red:     '0xff7a93'
      green:   '0xb9f27c'
      yellow:  '0xff9e64'
      blue:    '0x7da6ff'
      magenta: '0xbb9af7'
      cyan:    '0x0db9d7'
      white:   '0xacb0d0'

  tokyo-night-storm: &tokyo-night-storm
    # Default colors
    primary:
      background: '0x24283b'
      foreground: '0xa9b1d6'

    # Normal colors
    normal:
      black:   '0x32344a'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan:    '0x449dab'
      white:   '0x9699a8'

    # Bright colors
    bright:
      black:   '0x444b6a'
      red:     '0xff7a93'
      green:   '0xb9f27c'
      yellow:  '0xff9e64'
      blue:    '0x7da6ff'
      magenta: '0xbb9af7'
      cyan:    '0x0db9d7'
      white:   '0xacb0d0'
  night-owl: &night-owl
    primary:
      background: "#011627"
      foreground: "#d6deeb"

    # Cursor colors
    cursor:
      text: CellBackground
      cursor: CellForeground

    # Vi mode cursor colors
    vi_mode_cursor:
      text: CellBackground
      cursor: "#22da6e"

    # Selection colors
    selection:
      text: "#ffffff"
      background: "#0d486e"

    # Search colors
    search:
      matches:
        foreground: "#000000"
        background: "#22da6e"

        focused_match:
          foreground: "#ffffff"
          background: "#22da6e"

      bar:
        foreground: "#ffffff"
        background: "#1d3b53"

    # Normal colors
    normal:
      black: "#011627"
      red: "#EF5350"
      green: "#22da6e"
      yellow: "#c5e478"
      blue: "#82AAFF"
      magenta: "#C792EA"
      cyan: "#21c7a8"
      white: "#ffffff"

    # Bright colors
    bright:
      black: "#575656"
      red: "#EF5350"
      green: "#22da6e"
      yellow: "#ffeb95"
      blue: "#82AAFF"
      magenta: "#C792EA"
      cyan: "#7fdbca"
      white: "#ffffff"

  night-owl-light: &night-owl-light
    primary:
      background: "#F6F6F6"
      foreground: "#403f53"

    # Cursor colors
    cursor:
      text: CellBackground
      cursor: "#90A7B2"

    # Vi mode cursor colors
    vi_mode_cursor:
      text: CellBackground
      cursor: "#08916a"

    # Selection colors
    selection:
      text: "#000000"
      background: "#E0E0E0"

    # Search colors
    search:
      matches:
        foreground: "#F6F6F6"
        background: "#08916a"

        focused_match:
          foreground: "#000000"
          background: "#08916a"

      bar:
        foreground: "#403f53"
        background: "#E0E0E0"

    # Normal colors
    normal:
      black: "#403f53"
      red: "#de3d3b"
      green: "#08916a"
      yellow: "#daaa01"
      blue: "#288ed7"
      magenta: "#d6438a"
      cyan: "#2AA298"
      white: "#F0F0F0"

    # Bright colors
    bright:
      black: "#403f53"
      red: "#de3d3b"
      green: "#08916a"
      yellow: "#daaa01"
      blue: "#288ed7"
      magenta: "#d6438a"
      cyan: "#2AA298"
      white: "#F0F0F0"
  ayu_dark:
    &ayu_dark
    primary:
      background: '0x0f1419'
      foreground: '0xe6e1cf'
    normal:
      black: '0x000000'
      red: '0xf34a4a'
      green: '0xbae67e'
      yellow: '0xffee99'
      blue: '0x73d0ff'
      magenta: '0xd4bfff'
      cyan: '0x83CEC6'
      white: '0xf2f2f2'
    bright:
      black: '0x737d87'
      red: '0xff3333'
      green: '0xc2d94c'
      yellow: '0xe7c547'
      blue: '0x59c2ff'
      magenta: '0xb77ee0'
      cyan: '0x5ccfe6'
      white: '0xffffff'
  papercolor_light:
    &papercolor_light
    primary:
      background: '0xeeeeee'
      foreground: '0x4d4d4c'
    cursor:
      text: '0xf3f3f3'
      cursor: '0x4d4d4c'
    normal:
      black: '0xededed'
      red: '0xd7005f'
      green: '0x718c00'
      yellow: '0xd75f00'
      blue: '0x4271ae'
      magenta: '0x8959a8'
      cyan: '0x3e999f'
      white: '0x4d4d4c'

    # Bright colors
    bright:
      black: '0x949494'
      red: '0xd7005f'
      green: '0x718c00'
      yellow: '0xd75f00'
      blue: '0x4271ae'
      magenta: '0x8959a8'
      cyan: '0x3e999f'
      white: '0xf5f5f5'
  gruvbox_light:
    &gruvbox_light
    primary:
      background: '#fbf1c7'
      foreground: '#3c3836'
    normal:
      black: '#fbf1c7'
      red: '#cc241d'
      green: '#98971a'
      yellow: '#d79921'
      blue: '#458588'
      magenta: '#b16286'
      cyan: '#689d6a'
      white: '#7c6f64'
    bright:
      black: '#928374'
      red: '#9d0006'
      green: '#79740e'
      yellow: '#b57614'
      blue: '#076678'
      magenta: '#8f3f71'
      cyan: '#427b58'
      white: '#3c3836'
  gruvbox_dark:
    &gruvbox_dark
    primary:
      background: '#282828'
      foreground: '#ebdbb2'
    normal:
      black: '#282828'
      red: '#cc241d'
      green: '#98971a'
      yellow: '#d79921'
      blue: '#458588'
      magenta: '#b16286'
      cyan: '#689d6a'
      white: '#a89984'
    bright:
      black: '#928374'
      red: '#fb4934'
      green: '#b8bb26'
      yellow: '#fabd2f'
      blue: '#83a598'
      magenta: '#d3869b'
      cyan: '#8ec07c'
      white: '#ebdbb2'
  pencil_light:
    &pencil_light
    primary:
      background: '#f1f1f1'
      foreground: '#424242'
    normal:
      black: '#212121'
      red: '#c30771'
      green: '#10a778'
      yellow: '#a89c14'
      blue: '#008ec4'
      magenta: '#523c79'
      cyan: '#20a5ba'
      white: '#e0e0e0'
    bright:
      black: '#212121'
      red: '#fb007a'
      green: '#5fd7af'
      yellow: '#f3e430'
      blue: '#20bbfc'
      magenta: '#6855de'
      cyan: '#4fb8cc'
      white: '#f1f1f1'
  rigel:
    &rigel
    primary:
      background: '0x002635'
      foreground: '0xe6e6dc'
    normal:
      black:   '0x00384d'
      red:     '0xc43061'
      green:   '0x7fc06e'
      yellow:  '0xf08e48'
      blue:    '0x1c8db2'
      magenta: '0xc694ff'
      cyan:    '0x00cccc'
      white:   '0x77929e'
    bright:
      black:   '0x517f8d'
      red:     '0xff5a67'
      green:   '0x9cf087'
      yellow:  '0xffcc1b'
      blue:    '0x7eb2dd'
      magenta: '0xfb94ff'
      cyan:    '0x00ffff'
      white:   '0xb7cff9'
    cursor:
      text: "0x002635"
      cursor: "0xffcc1b"
  tender:
    &tender
    primary:
      background: '0x282828'
      foreground: '0xeeeeee'
    normal:
      black:   '0x282828'
      red:     '0xf43753'
      green:   '0xc9d05c'
      yellow:  '0xffc24b'
      blue:    '0xb3deef'
      magenta: '0xd3b987'
      cyan:    '0x73cef4'
      white:   '0xeeeeee'
    bright:
      black:   '0x4c4c4c'
      red:     '0xf43753'
      green:   '0xc9d05c'
      yellow:  '0xffc24b'
      blue:    '0xb3deef'
      magenta: '0xd3b987'
      cyan:    '0x73cef4'
      white:   '0xfeffff'

colors: *ayu_dark
